application: ym731-quora-application
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /.*
  script: ym731.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest